from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from datetime import datetime

def generate_pdf_report(
    filename,
    summary,
    findings,
    risk_score,
    metrics
):
    doc = SimpleDocTemplate(
        filename
    )

    styles = getSampleStyleSheet()

    content = []

    # ==========================
    # COVER PAGE
    # ==========================

    content.append(
        Paragraph(
            "AI SSDLC SECURITY REVIEW REPORT",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            f"Generated: {datetime.now()}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            f"Repository Risk Score: {risk_score}/100",
            styles["Heading2"]
        )
    )

    content.append(
        PageBreak()
    )

    # ==========================
    # EXECUTIVE SUMMARY
    # ==========================

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            summary,
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    # ==========================
    # RISK METRICS
    # ==========================

    content.append(
        Paragraph(
            "Risk Metrics",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            f"Critical Findings: {metrics['CRITICAL']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"High Findings: {metrics['HIGH']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"Medium Findings: {metrics['MEDIUM']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"Low Findings: {metrics['LOW']}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    # ==========================
    # TOP FINDINGS
    # ==========================

    content.append(
        Paragraph(
            "Top Security Findings",
            styles["Heading1"]
        )
    )

    for i, finding in enumerate(
        findings[:10],
        start=1
    ):
        content.append(
            Paragraph(
                f"Finding #{i}",
                styles["Heading2"]
            )
        )

        content.append(
            Paragraph(
                f"Severity: {finding.get('severity')}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"Issue: {finding.get('issue')}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"File: {finding.get('file')}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"Recommendation: {finding.get('recommendation')}",
                styles["BodyText"]
            )
        )

        content.append(
            Spacer(1, 10)
        )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by AI SSDLC Review Agent",
            styles["Italic"]
        )
    )

    doc.build(
        content
    )

    return filename

